# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

# Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# Method has too many lines.
MethodLength:
  Max: 15
